language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - ALCOTEST_SHOW_ERRORS=1
    - PINS="resp-server.dev:."
  matrix:
    - OCAML_VERSION=4.06 PACKAGE="resp-server.dev" TESTS=true
    - OCAML_VERSION=4.07 PACKAGE="resp-server.dev" TESTS=true
